#4 - Add test summary
nicoddemus/pytest-rich pull request #31
Opened 2022-03-15 14:19 UTC by bhavaniravi

Add a test summary at the end of the test suite.

I've attempted this to the best of my knowledge. Any suggestions, comments, improvements are welcomed

2022-03-16 18:54 UTC, nicoddemus commented
Here's the output:

![image](https://user-images.githubusercontent.com/1085180/158665784-9c99306c-5ce0-40ac-bd66-e0332a84558f.png)

2022-03-16 19:02 UTC, nicoddemus requested changes
Thanks @bhavaniravi overall looks nice, left a few request for changes though.

Also, can you please update the changelog? Thanks!

2022-03-16 19:02 UTC, nicoddemus commented on pytest_rich.py
> +                + Text(f"{nodeid} {''.join(errors)}", style="black")
Ditto here for black style

2022-03-16 19:02 UTC, nicoddemus commented on pytest_rich.py
> +        self.console.print(Rule("The End", characters="=", style="blue"))
This is of course a matter of taste, but I don't think we need this rule at the end of the session... if we do want to have it however, we might display the exit status instead (given by `pytest_sessionfinish`).

2022-03-17 18:42 UTC, nicoddemus commented on pytest_rich.py
> +                + total_text
A few suggestions, leaving them here to see what @joshuadavidthomas thinks:

1. We might consider changing `::` to `:`, so it reads `Total: 38 Success: 38 Failed: 0`.
2. We should be "smart" like pytest is, for example, if all tests pass, it shows only `64 passed`. If some failed, it shows `60 passed, 4 failed` and so on. So here we could use `Success: 38` if all passed, but show `Total: 38 Success: 30 Failed: 8` if some fail, for example.
3. We are not showing the time taken by the suite, which is often useful. We might leverage rich's abilities here and instead show a box with the summary. For example here's how [ward ](https://github.com/darrenburns/ward) does it: 
![image](https://user-images.githubusercontent.com/1085180/158873455-e82df289-9815-463d-8797-bcaa1c1fb84c.png)

2022-10-28 03:17 UTC, joshuadavidthomas requested changes
This is great @bhavaniravi! Sorry for the silence the past couple of months regarding your contribution. I've left some comments on my review and @nicoddemus's.

2022-10-28 03:17 UTC, joshuadavidthomas commented on pytest_rich.py
> +            )
Spacing is a bit off with the spaces in the total and failed `Text` objects:

![image](https://user-images.githubusercontent.com/19896267/198494076-0bbdf526-5aa7-4e7f-8f4f-7cba7bdbd8ef.png)

Could you change this to adding the spacing when printing to the console?

```python
total_text = Text(f"Total::{self.total_items_completed}", style="bold blue")
success_text = Text(
	f"Success::{self.total_items_completed - len(self.failed_reports)}",
    	style="bold green",
	)
failed_text = Text(f"Failed::{len(self.failed_reports)}", style="bold red")
self.console.print(
    Rule(
        total_text + " " + success_text + " " + failed_text,
        characters="=",
        style="blue",
    )
)
```

![image](https://user-images.githubusercontent.com/19896267/198494178-be845194-fa01-4fb9-93f6-b06eb444fa82.png)

2022-10-28 03:19 UTC, joshuadavidthomas commented on pytest_rich.py
> +                + total_text
@nicoddemus Yeah, I think the time would be useful, but may be worth tackling in a separate PR.

As far as the colons, yeah I agree, single is clearer.

2022-10-28 10:05 UTC, bhavaniravi commented
Currently looks like this

**All Pass**

![image](https://user-images.githubusercontent.com/10116000/198561663-3f23b096-066c-47d1-987a-902b828f96ad.png)

**Failures**

![image](https://user-images.githubusercontent.com/10116000/198561778-09b7eaba-f84c-407e-8f0a-c34552331f51.png)

**Dark Mode**

![image](https://user-images.githubusercontent.com/10116000/198561857-b573fd3b-5cef-458a-b5d8-9b5248a6e3bf.png)

2022-10-28 14:11 UTC, joshuadavidthomas approved these changes
LGTM, thanks!

2022-10-28 14:15 UTC, merged